
[[audits.bincode]]
who = "Oleksii Filonenko <oleksii.filonenko@fuel.sh>"
criteria = "safe-to-run"
version = "1.3.3"
aggregated-from = "https://raw.githubusercontent.com/FuelLabs/fuel-types/oleksii/supply-chain/supply-chain/audits.toml"

[[audits.itoa]]
who = "Oleksii Filonenko <oleksii.filonenko@fuel.sh>"
criteria = "safe-to-run"
version = "1.0.2"
aggregated-from = "https://raw.githubusercontent.com/FuelLabs/fuel-types/oleksii/supply-chain/supply-chain/audits.toml"

[[audits.ppv-lite86]]
who = "Oleksii Filonenko <oleksii.filonenko@fuel.sh>"
criteria = "safe-to-deploy"
version = "0.2.16"
aggregated-from = "https://raw.githubusercontent.com/FuelLabs/fuel-types/oleksii/supply-chain/supply-chain/audits.toml"

[[audits.rand]]
who = "Oleksii Filonenko <oleksii.filonenko@fuel.sh>"
criteria = "safe-to-deploy"
version = "0.8.5"
aggregated-from = "https://raw.githubusercontent.com/FuelLabs/fuel-types/oleksii/supply-chain/supply-chain/audits.toml"

[[audits.rand_chacha]]
who = "Oleksii Filonenko <oleksii.filonenko@fuel.sh>"
criteria = "safe-to-deploy"
version = "0.3.1"
aggregated-from = "https://raw.githubusercontent.com/FuelLabs/fuel-types/oleksii/supply-chain/supply-chain/audits.toml"

[[audits.rand_core]]
who = "Oleksii Filonenko <oleksii.filonenko@fuel.sh>"
criteria = "safe-to-deploy"
version = "0.6.3"
aggregated-from = "https://raw.githubusercontent.com/FuelLabs/fuel-types/oleksii/supply-chain/supply-chain/audits.toml"

[[audits.ryu]]
who = "Oleksii Filonenko <oleksii.filonenko@fuel.sh>"
criteria = "safe-to-run"
version = "1.0.11"
aggregated-from = "https://raw.githubusercontent.com/FuelLabs/fuel-types/oleksii/supply-chain/supply-chain/audits.toml"

[[audits.serde]]
who = "Oleksii Filonenko <oleksii.filonenko@fuel.sh>"
criteria = "safe-to-deploy"
version = "1.0.137"
aggregated-from = "https://raw.githubusercontent.com/FuelLabs/fuel-types/oleksii/supply-chain/supply-chain/audits.toml"

[[audits.serde_derive]]
who = "Oleksii Filonenko <oleksii.filonenko@fuel.sh>"
criteria = "safe-to-deploy"
version = "1.0.137"
aggregated-from = "https://raw.githubusercontent.com/FuelLabs/fuel-types/oleksii/supply-chain/supply-chain/audits.toml"

[[audits.serde_json]]
who = "Oleksii Filonenko <oleksii.filonenko@fuel.sh>"
criteria = "safe-to-run"
version = "1.0.81"
aggregated-from = "https://raw.githubusercontent.com/FuelLabs/fuel-types/oleksii/supply-chain/supply-chain/audits.toml"

[[audits.syn]]
who = "Oleksii Filonenko <oleksii.filonenko@fuel.sh>"
criteria = "safe-to-deploy"
version = "1.0.96"
aggregated-from = "https://raw.githubusercontent.com/FuelLabs/fuel-types/oleksii/supply-chain/supply-chain/audits.toml"

[[audits.unicode-ident]]
who = "Oleksii Filonenko <oleksii.filonenko@fuel.sh>"
criteria = "safe-to-deploy"
version = "1.0.0"
aggregated-from = "https://raw.githubusercontent.com/FuelLabs/fuel-types/oleksii/supply-chain/supply-chain/audits.toml"
